//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期末專案0924
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGuestReviews
    {
        public int cGuestRevSN { get; set; }
        public int cGuestSN { get; set; }
        public string cGuestRevText { get; set; }
        public int cGuestRatingService { get; set; }
        public Nullable<int> cGuestRatingFacility { get; set; }
        public Nullable<int> cGuestRatingCleanliness { get; set; }
        public Nullable<int> cGuestRatingComfort { get; set; }
        public int cGuestRatingLocation { get; set; }
        public int cGuestRatingCP { get; set; }
        public double cGuestRatingAverage { get; set; }
        public System.DateTime cGuestRevDate { get; set; }
        public int cHotelRoomTypeSN { get; set; }
        public string cGuestRevHotelReason { get; set; }
        public string cOrderID { get; set; }
    }
}
