//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期末專案0924
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHotelInfomation
    {
        public int cHotelSN { get; set; }
        public Nullable<int> cFirmSN { get; set; }
        public string cFirmTaxID { get; set; }
        public string cHotelName { get; set; }
        public string cHotelNameEN { get; set; }
        public string cHotelCity { get; set; }
        public string cHotelAdress { get; set; }
        public Nullable<System.DateTime> cHotelCreationDate { get; set; }
        public string cHotelInfoPhotoName { get; set; }
        public string cHotelInfoPhotoFileName { get; set; }
        public string cHotelPhone { get; set; }
        public string cHotelAverageRating { get; set; }
        public string cHotelRatingOfPeople { get; set; }
        public string cHotelType { get; set; }
        public Nullable<bool> cHotelBarrierfree { get; set; }
        public string cHotelVisitors { get; set; }
    }
}
