//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST3
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAdvertising
    {
        public int cADSN { get; set; }
        public string cFirmSN { get; set; }
        public string cADName { get; set; }
        public string cADFileName { get; set; }
        public Nullable<System.DateTime> cADStartDate { get; set; }
        public Nullable<System.DateTime> cADDueDate { get; set; }
        public string cADActionDate { get; set; }
        public Nullable<bool> cADStatus { get; set; }
        public string cADGroup { get; set; }
        public string cADURL { get; set; }
        public Nullable<System.DateTime> cADCreateDate { get; set; }
        public Nullable<System.DateTime> cADEditDate { get; set; }
    }
}
