//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期末專題_旅遊網
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGuestAccountInfomation
    {
        public int cGuestSN { get; set; }
        public string cGuestEmail { get; set; }
        public string cGuestPWDHash { get; set; }
        public string cGuestPWDSalt { get; set; }
        public Nullable<System.DateTime> cGuestAccountCreationDate { get; set; }
        public string cGuestLastName { get; set; }
        public string cGuestFirstName { get; set; }
        public string cGuestLastNameEN { get; set; }
        public string cGuestFirstNameEN { get; set; }
        public System.DateTime cGuestBirth { get; set; }
        public string cGuestCitizenship { get; set; }
        public string cGuestID { get; set; }
        public string cGuestGender { get; set; }
        public int cGuestPhoneNumber { get; set; }
    }
}
