//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期末專題_旅遊網
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHotelRoomPhoto
    {
        public int cHotelRoomPhotoSN { get; set; }
        public int cHotelRoomTypeSN { get; set; }
        public string cHotelRoomPhotoName { get; set; }
        public byte[] cHotelRoomPhoto { get; set; }
        public int cHotelSN { get; set; }
        public string cHotelRoomTypeName { get; set; }
    }
}
