//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期末專題_旅遊網
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHotelRoomType
    {
        public int cHotelRoomTypeSN { get; set; }
        public Nullable<int> cFirmSN { get; set; }
        public int cHotelSN { get; set; }
        public string cHotelRoomTypeName { get; set; }
        public int cHotelRoomCount { get; set; }
        public int cHotelRoomContain { get; set; }
        public int cHotelRoomContainAldults { get; set; }
        public int cHotelRoomContainChiidren { get; set; }
        public int cHotelRoomTypePriceOfWeekdays { get; set; }
        public int cHotelRoomTypePriceOfHoliday { get; set; }
        public int cHotelRoomTypePriceOfFestival { get; set; }
    }
}
