//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期末專題_旅遊網
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStaffProfile
    {
        public int cStaffProfileSN { get; set; }
        public string cStaffAccountID { get; set; }
        public string cStaffPWD { get; set; }
        public byte[] cStaffPWDHash { get; set; }
        public byte[] cStaffPWDSalt { get; set; }
        public Nullable<System.DateTime> cStaffProfileCreationDate { get; set; }
        public string cStaffLastName { get; set; }
        public string cStaffFirstName { get; set; }
        public string cStaffID { get; set; }
        public string cStaffGender { get; set; }
        public string cStaffCellphone { get; set; }
        public string cStaffResidenceAddress { get; set; }
        public string cStaffMailingAddress { get; set; }
        public byte[] cStaffEmail { get; set; }
        public Nullable<int> cJobTitleSN { get; set; }
        public string cStaffERContactName { get; set; }
        public string cStaffERContactRelationship { get; set; }
        public string cStaffERContactNumber { get; set; }
        public Nullable<System.DateTime> cStaffBirth { get; set; }
    }
}
