//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期末專題_旅遊網
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserOrder
    {
        public int cOrderSN { get; set; }
        public int cOrderID { get; set; }
        public int cGuestSN { get; set; }
        public Nullable<System.DateTime> cOrderDate { get; set; }
        public Nullable<System.DateTime> cCheckInDate { get; set; }
        public Nullable<System.DateTime> cCheckOutDate { get; set; }
        public string cOrderStatus { get; set; }
        public Nullable<int> cStaffProfileSN { get; set; }
        public int cHotelRoomTypeSN { get; set; }
        public string cOrderNotes { get; set; }
        public int cOrderPrice { get; set; }
        public Nullable<int> cStayDays { get; set; }
    }
}
